generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SurveyAnswer
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          survey_answer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        value: { type: mixed }
        list_survey: { label: Survey }
        list_transaction_id: { label: Transaction }
        list_contact: { label: Contact }
      list:
        display: [_list_survey, _list_transaction_id, _list_contact, lang, Query, value, updated_at]
        actions:        []
        object_actions:
          _delete_answer:
            action: deleteAnswer
            ui-icon: trash
        batch_actions:  []
        sort: ['s.name, q.rank, updated_at', '']
        max_per_page: 10
      filter:
        display: [survey_id, contact_id, survey_query_id, lang, value, updated_at]
      form:    ~
      edit:    ~
      new:     ~
